### ISSUE TITLE
New module for accessing predefined constants

### ISSUE THREAD

**Issue by witling** [lausek/lowebf#4]
**Idea:** Provide functionality for reading and converting [superglobal](https://www.php.net/language.variables.superglobals) values. 

```php
// version 1
$pageId = $env->variables()->get()->getAsInteger("pageId")->unwrapOr(1);

// version 2
$pageId = $env->variables()->get()->asInteger("pageId")->unwrapOr(1);

// version 3
$pageId = $env->variables()->get("pageId")->mapToInteger()->unwrapOr(1);
```

#### Alternative Names

- `superglobals`
- `predefined`
- `globals`

### Mockup

```php
class VariableModule extends Module {
    // $_GET variable
    public function get() -> Array;
    // $_POST variable
    public function post() -> Array;
    // $_SERVER variable
    public function server() -> Array;
}
```

```php
class Array {
    public static function from(array &$data) : Array;
    public function getAsInteger(string $name) : Result<int>;
    public function getAsFloat(string $name) : Result<float>;
    // ...
}
```

**Comment by lausek** [comment]
- Changed the name to `GlobalsModule` as it is shorter
- Added `get($key)`, `post($key)` and `server($key)` in first implementation returning a Result
- Added `mapToInteger`, `mapToString`, `mapToBool` methods on Result for type conversions
- Added `unwrapOr($default)` to specify a default value for failed results
